apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecomarket
  labels:
    app: user-service
    tier: backend
    service: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
        service: user
    spec:
      serviceAccountName: ecomarket-service-account
      containers:
      - name: user-service
        image: ecomarket/user-service:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ecomarket-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: ecomarket-secrets
              key: MONGODB_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ecomarket-secrets
              key: JWT_SECRET
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ecomarket-secrets
              key: GOOGLE_CLIENT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecomarket
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: user-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: ecomarket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
