# Prometheus Configuration for Node Exporter Scraping
# This configuration scrapes Node exporter endpoints from the microservices

global:
  scrape_interval: 15s        # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s    # Evaluate rules every 15 seconds

# Scrape configuration for Node exporters
scrape_configs:
  # Job for Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job for Node exporter - main host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Job for Node exporters from microservices
  # Assuming each service exposes Node exporter on port 9100
  - job_name: 'microservices-node-exporter'
    static_configs:
      - targets: 
          - 'user-service:9100'
          - 'order-service:9100'  
          - 'product-catalog-service:9100'
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Alternative configuration for Docker Compose setup
  # Uncomment if services are running in Docker with service discovery
  # - job_name: 'docker-node-exporters'
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       refresh_interval: 30s
  #   relabel_configs:
  #     - source_labels: [__meta_docker_container_name]
  #       target_label: instance
  #     - source_labels: [__meta_docker_container_label_com_docker_compose_service]
  #       target_label: service

# Rule files (if you want to add alerting rules later)
# rule_files:
#   - "alert_rules.yml"

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
